"""github telemetry repo fields

Revision ID: 2007c1324147
Revises: 89e2d0819f27
Create Date: 2026-08-29 21:09:06.352563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2007c1324147'
down_revision: Union[str, Sequence[str], None] = '89e2d0819f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_owner_id'), 'events', ['owner_id'], unique=False)
    op.create_index(op.f('ix_events_project_id'), 'events', ['project_id'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('github_connections',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('github_login', sa.String(length=255), nullable=True),
    sa.Column('installation_id', sa.BigInteger(), nullable=True),
    sa.Column('access_token_enc', sa.Text(), nullable=False),
    sa.Column('refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('access_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('refresh_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_github_connections_owner_id'), 'github_connections', ['owner_id'], unique=True)
    op.create_table('oauth_states',
    sa.Column('state', sa.String(length=64), nullable=False),
    sa.Column('owner_id', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.add_column('projects', sa.Column('repo_id', sa.BigInteger(), nullable=True))
    op.add_column('projects', sa.Column('repo_owner', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('repo_name', sa.String(length=255), nullable=True))
    op.add_column('projects', sa.Column('repo_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'repo_url')
    op.drop_column('projects', 'repo_name')
    op.drop_column('projects', 'repo_owner')
    op.drop_column('projects', 'repo_id')
    op.drop_table('oauth_states')
    op.drop_index(op.f('ix_github_connections_owner_id'), table_name='github_connections')
    op.drop_table('github_connections')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_project_id'), table_name='events')
    op.drop_index(op.f('ix_events_owner_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
