"""session capsule loop fields

Revision ID: 89e2d0819f27
Revises: b4f13d68c22a
Create Date: 2026-08-29 20:50:40.236661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89e2d0819f27'
down_revision: Union[str, Sequence[str], None] = 'b4f13d68c22a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('capsules', sa.Column('session_id', sa.String(length=36), nullable=True))
    op.add_column('capsules', sa.Column('next_action', sa.Text(), nullable=False))
    op.add_column('capsules', sa.Column('workspace_pointer', sa.Text(), nullable=True))
    op.add_column('capsules', sa.Column('done_when', sa.Text(), nullable=True))
    op.add_column('capsules', sa.Column('estimated_minutes', sa.Integer(), nullable=True))
    op.add_column('capsules', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('capsules', sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('capsules', sa.Column('consumed_by_session_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_capsules_status'), 'capsules', ['status'], unique=False)
    op.create_foreign_key(None, 'capsules', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.add_column('sessions', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('sessions', sa.Column('started_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('sessions', sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_column('sessions', 'ended_at')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'status')
    op.drop_constraint(None, 'capsules', type_='foreignkey')
    op.drop_index(op.f('ix_capsules_status'), table_name='capsules')
    op.drop_column('capsules', 'consumed_by_session_id')
    op.drop_column('capsules', 'consumed_at')
    op.drop_column('capsules', 'status')
    op.drop_column('capsules', 'estimated_minutes')
    op.drop_column('capsules', 'done_when')
    op.drop_column('capsules', 'workspace_pointer')
    op.drop_column('capsules', 'next_action')
    op.drop_column('capsules', 'session_id')
    # ### end Alembic commands ###
